environment:
  PYTEST_ADDOPTS: "--pep8"
  matrix:
    - PYTHON: "C:\\Python36"
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install pyyaml"
build: off
test_script:
  - "%PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe setup.py install"
