environment:
  matrix:
    - PYTHON: "C:\\Python36"
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest"
  - "%PYTHON%\\python.exe setup.py install"
